### ISSUE TITLE
Should the ebin version be checked?

### ISSUE THREAD

**Issue by Licenser** [erlef/rebar3_hex#14]
The hex plugin still checks ./ebin/*.app for the app version during publish and cut, how I understand it with rebar3 that should all be in _build/default/... 

This difference in behavior can lead to some confusion when a old ebin folder exists and cut/publish refuses to pick up the new version that rebar3 already knows about.

**Comment by tsloughter** [comment]
The plugin isn't the one responsible for "checking" the app file. It uses `rebar_app_info` to get the vsn. Which can't know if `ebin/*.app` is accurate or not and has to assume it is if it exists.

**Comment by starbelly** [comment]
@tsloughter Can this be closed?

**Comment by tsloughter** [comment]
Yea, I think so.
