### ISSUE TITLE
Where to put the plugin configuration

### ISSUE THREAD

**Issue by MSch** [erlef/rebar3_hex#15]
https://github.com/hexpm/rebar3_hex/blob/f48d66a9bd2b5b7c5db4eaeed7b917d2b7b20f03/README.md#usage says to put `{plugins, [rebar3_hex]}.` in my project's `rebar.config`.

http://www.rebar3.org/docs/using-available-plugins#hex-package-management says

> For the `hex` plugin it is suggested to place the entry in the global `rebar3` config which should be made as `~/.config/rebar3/rebar.config`.

I recently published http://github.com/ferd/backoff to hex.pm so I could easily depend on it from my Elixir/mix project. I then got  a `WARN:  Missing plugins: [rebar3_hex]` message when building the dependency using mix, so I've removed `{plugins, [rebar3_hex]}.` from backoff's `rebar.config` and rely on `~/.config/rebar3/rebar.config`.

What is the best practice approach here?

**Comment by ferd** [comment]
The global plugin approach is the one favoured by rebar3

**Comment by tsloughter** [comment]
Merged your PR, so closing this. thanks!
