### ISSUE TITLE
Publishing using an unauthorized user crashes

### ISSUE THREAD

**Issue by eproxus** [erlef/rebar3_hex#150]
Publishing using an unauthorized user crashes:

```
...
Be aware, you are publishing to the public Hexpm repository.
Before publishing, please read Hex CoC: https://hex.pm/policies/codeofconduct
Proceed? ("Y")> y
Local Password:
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> Uncaught error: {case_clause,
                                {ok,{403, ...
```

* `rebar3` v3.13.1 on Erlang/OTP 22 Erts 10.6.4
* `rebar3_hex` v6.93
* `hex_core` v0.6.8
* `verl` v1.0.2

**Comment by starbelly** [comment]
Yeah, definitely shouldn't make it that far. Will look into this ASAP.

**Comment by starbelly** [comment]
@eproxus I just tried to replicate this but was met with the expected behavior: 

```
===> No write key found for user. Be sure to authenticate first with: rebar3 hex user auth
```

Can you give steps to reproduce?

**Comment by eproxus** [comment]
I get that message too when I'm not authorized at all. However, this error comes from being logged in as a different user that doesn't have permissions. Did you try that?

I guess "unauthorized user"  wasn't very clear 😄

**Comment by starbelly** [comment]
@eproxus Ahh yeah, that makes sense. Let me give this a go in a bit..

**Comment by starbelly** [comment]
@eproxus Replicated, patch opened, just need to add a test then get it out the door 👍
