### ISSUE TITLE
Report status code when user auth fails

### ISSUE THREAD

**Issue by sanmiguel** [erlef/rebar3_hex#17]
Currently when `rebar3 hex user auth` fails, no status code is reported (also no info is printed with `DEBUG=1` set). It would be more pleasing to get some feedback on what went wrong.

FWIW `mix hex.user auth` reports:

```
Username: sanmiguel
Password:
Generating API key...
Generation of API key failed (401)
Authentication failed (401)
```

**Comment by tsloughter** [comment]
Thanks, I'll get this added soon.

**Comment by tsloughter** [comment]
Added in `v1.6.1`.
