### ISSUE TITLE
Error "Proceed? ("Y")> I didn't get that. This boolean kind of question."

### ISSUE THREAD

**Issue by mworrell** [erlef/rebar3_hex#175]
Trying to publish a Hex package using:

```
rebar3 hex publish -r hexpm --yes
```

we get the error:

```
Proceed? ("Y")> I didn't get that. This boolean kind of question.
```

This used to work.

What is changed in the arguments?

(Tried `rebar3 help hex publish` but that crashes)

**Comment by tsloughter** [comment]
Sorry about that, clearly we need better tests :). I've opened a PR to fix it.

**Comment by mworrell** [comment]
That is a quick fix!  Thanks!

Now I'll wait for the release, then our own releases via GH actions work again.

**Comment by tsloughter** [comment]
Can you use master for the time being instead? I'd like to fix some of the other issues before a new release.

**Comment by mworrell** [comment]
What is the best way to switch rebar_hex to master?
We download rebar3 from aws during our build step, maybe we can specify the Hex plugin somewhere.

**Comment by tsloughter** [comment]
You must be specifying the hex plugin somewhere already. And you can switch that to a git dep pointing to master. The plugins are the same format as a regular dep just under the `plugins` or `project_plugins` key.

**Comment by mworrell** [comment]
Ah, maybe hidden somewhere, will search :-)
