### ISSUE TITLE
undef when calling rebar_packages:registry

### ISSUE THREAD

**Issue by ethercrow** [erlef/rebar3_hex#19]
Here `rebar3_hex_search:do` calls `rebar_packages:registry`
https://github.com/hexpm/rebar3_hex/blob/master/src/rebar3_hex_search.erl#L31
but rebar_packages doesn't export or even have such function
https://github.com/rebar/rebar3/blob/master/src/rebar_packages.erl#L3

How does it work?

**Comment by tsloughter** [comment]
Ah, it does not work any more. Need to add tests so this doesn't happen again.

**Comment by tsloughter** [comment]
Should be fixed now, I published rebar3_hex 1.7.1

**Comment by ethercrow** [comment]
`rebar3 hex search` now works for me, thanks
