### ISSUE TITLE
rebar3 Hex installation instructions don't work on Windows

### ISSUE THREAD

**Issue by lpil** [erlef/rebar3_hex#191]
Hello!

I'm following the instructions on this page: https://hex.pm/docs/rebar3_usage

After adding the plugin to my `~/.config/rebar3/rebar.config` file (`C:\Users\louis.pilfold\.config\rebar3\rebar3.config`) rebar3 does not install the Hex plugin, so I am unable to publish a package using it.

```
❯ rebar3 hex publish
===> Command hex not found
```

Original issue: https://github.com/hexpm/hex/issues/828

**Comment by ferd** [comment]
can you show what the config file looks like?

**Comment by lpil** [comment]
Sure thing

```erlang
% cat C:\Users\louis.pilfold\.config\rebar3\rebar3.config
{plugins, [rebar3_hex]}.
```

**Comment by lpil** [comment]
Oops, it's a typo! My bad
