### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlef/rebar3_hex#197]
Thanks for merging https://github.com/tsloughter/rebar3_hex/pull/196.

Would it be possible to cut a release, to have this new version imported where I found the issue?

Cheers.

**Comment by starbelly** [comment]
@paulo-ferraz-oliveira Yup! We can :) Thanks for the PR.

**Comment by starbelly** [comment]
Done. New release cut on github and pushed to hex.pm ❤️

**Comment by paulo-ferraz-oliveira** [comment]
Thanks, Bryan.
