### ISSUE TITLE
No hex config written when registering

### ISSUE THREAD

**Issue by kellymclaughlin** [erlef/rebar3_hex#2]
I registered a new hex account and received the confirmation email as expected, but no hex configuration was written. Glancing over the source, the only place I see a call to `rebar3_hex_config:write` is in the [`deauth` function](https://github.com/tsloughter/rebar3_hex/blob/master/src/rebar3_hex_user.erl#L95). 

Here is the output of a few commands after I completed registration and confirm via email.

```
$ ./rebar3 hex user whoami

```

```
 $ ./rebar3 hex config username
username: 
```

Shouldn't the register process write a config or is writing a config file expected to be a manual step?

**Comment by tsloughter** [comment]
Hm, weird, it should be done here https://github.com/tsloughter/rebar3_hex/blob/master/src/rebar3_hex_user.erl#L170

**Comment by kellymclaughlin** [comment]
Oh, I bet the call to `file:write_file` returned an `{error, enoent}` because I don't have a `.hex` directory in my $HOME.

**Comment by tsloughter** [comment]
Argh, yea, my bad. I'll add a ensure_dir and match on ok for write.

**Comment by tsloughter** [comment]
Updated. You should be able to get a config with `rebar3 hex user auth` though.

**Comment by kellymclaughlin** [comment]
Yep, that works. Thanks!
