### ISSUE TITLE
add a possibility to override the default package name on publish

### ISSUE THREAD

**Issue by benoitc** [erlef/rebar3_hex#21]
Following the discussion in rebar/rebar3#908 , I open a ticket here to track the possible addition of a new metadata to the `app.src`possibly named `package_name`. The main goal of this feature is to set the package name in hex independently of the application name itself.

**Comment by tsloughter** [comment]
@benoitc can you try version 1.9.0? You should be able to use `{pkg_name, <name>}` in the `.app.src` now to set the package name.

**Comment by benoitc** [comment]
thanks for the change! Publishing was working, however the `--revert`command was not using the alternate path. #22 should fix it.
