### ISSUE TITLE
Support for exclude_patterns?

### ISSUE THREAD

**Issue by oubiwann** [erlef/rebar3_hex#233]
Hex has the ability to exclude files from hex.pm package uploads (e.g, image files) via the `exclude_patterns` directive:
* https://hexdocs.pm/hex/Mix.Tasks.Hex.Build.html#module-package-configuration

Is this currently possible with rebar3_hex?

If not, could support for this be added?

Note that I tried adding the directive to my `src/*.app.src` file in a project but had no success ... might be doing in wrong? `git grep` and Google searches turned up nothing for rebar3 + hex.

**Comment by oubiwann** [comment]
The only way I've found to get what I need is explicitly list the files that should be included in the pages with `{files: [ ... ]}` in the `*.app.src` file :-(

**Comment by ferd** [comment]
There's also an `exclude_files` option, which doesn't use patterns but lets you explicitly drop some files from everything.

**Comment by starbelly** [comment]
@oubiwann What Fred said, but also I'm about to be in this area and we're about to break the interface for v7, so should be to make this happen.

**Comment by starbelly** [comment]
This is actually already supported, it simply was not documented, it is now per a PR about I'm about to send up. `exclude_regexps` may be set in `.app.src`.

**Comment by starbelly** [comment]
I do like the name `exclude_patterns` better though, let's make it so!
