### ISSUE TITLE
Running `rebar3 hex publish` outside a project creates empty rebar.lock

### ISSUE THREAD

**Issue by eproxus** [erlef/rebar3_hex#234]
If you run `rebar3 hex publish` in a directory that is not a Rebar/Erlang application, it will create an empty `rebar.lock` file:

```sh
$ cd /tmp
$rebar3 hex publish
===> Verifying dependencies...
Select application(s):
------------
A) All
[1-0] or (A)ll  ("A")> ^C
BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution
^C⏎
$ cat rebar.lock
[].
```

The initial prompt is probably also wrong since there are no applications to select from in the first place.

**Comment by tsloughter** [comment]
The lock will be unrelated. It'll need a fix in rebar3.

The hex plugin simply depends on certain rebar3 steps (providers) and they are called without any part of the hex plugin running before them.

But the `publish` should definitely abort if no apps are found. I'm guessing it is just checking if `[App]` is the match and forgetting about `[]`.

**Comment by eproxus** [comment]
@tsloughter Do you want me to open an issues on Rebar 3?

**Comment by tsloughter** [comment]
Yea. There might already been one, this is something I've wanted to fix for a while.

**Comment by ferd** [comment]
I think rebar3 always locks dependencies, even when there are none found.. running it outside of a project just makes teh whole deps scan return "no deps found or declared" (since there's no rebar.config file) and a lockfile is still created.

**Comment by starbelly** [comment]
https://github.com/erlang/rebar3/pull/2662
