### ISSUE TITLE
Remind users to upload docs after publishing

### ISSUE THREAD

**Issue by ericmj** [erlef/rebar3_hex#24]

**Comment by starbelly** [comment]
Hmm, this is an old issue... I don't think hex reminds you to publish docs? I can't remember, but didn't see any related code for that. It looked like in hex you either explicitly specify the package and it publishes, without a reminder... or it tries to build the docs, publish the package, and the docs... is that correct @ericmj ?

**Comment by tsloughter** [comment]
mix hex will always publish the docs when publishing a package.

**Comment by starbelly** [comment]
@tsloughter hmmm... that's not what I thought I saw... but gonna go with my eyes were deceiving me. Either way, should we follow suite? Is there a reason we do not yet?

**Comment by tsloughter** [comment]
Reason I didn't was that so many erlang projects likely fail when edoc is run on them.

But it might be a good idea since it happens after the initial publishing of the package, so it won't block publishing. It will just ensure that if docs are able to be built they get published too.

**Comment by starbelly** [comment]
Right, we are on the same page 👍

**Comment by ericmj** [comment]
@tsloughter is correct. `mix hex.publish` will publish both package and docs, and will stop the publish if it fails to build the docs. `mix hex.publish package` publishes only package, `mix hex.publish docs` publishes only docs (useful when doing docs fixes after publishing).

**Comment by starbelly** [comment]
@ericmj aye... though I don't think it's a good idea to let @tsloughter know he's correct.
