### ISSUE TITLE
add the possibility to ignore some files when publishing

### ISSUE THREAD

**Issue by benoitc** [erlef/rebar3_hex#25]
When you don't pay attention, some none files may be included in the source package. For example .so in priv, .o in c_src ...

Having a .hexignore would be useful for that. Thoughts?

**Comment by tsloughter** [comment]
This was brought up again, definitely a feature that should be added soon. Not sure when I'll get t oit.

**Comment by saleyn** [comment]
Has this feature been implemented?  I see it being referenced [here](https://github.com/erlang/rebar3/issues/1202#issuecomment-220834857) but can't find any documentation.

**Comment by saleyn** [comment]
As far as I understand this feature was implemented with the `exclude_files` config option. Could you point to an example where that option is supposed to go in the config file and whether is accepts wildcards?

**Comment by starbelly** [comment]
This was indeed resolved via `exclude_files` feature. Closing as resolved. Please re-open if there is another issue.
