### ISSUE TITLE
rebar3 hex docs: Improve error message when using {vsn, "git"}

### ISSUE THREAD

**Issue by wojtekmach** [erlef/rebar3_hex#252]
I have:

```erlang
%% src/<app>.app.src
{vsn, "git"}
```

I was running the following:

```
~/src/telemetry[main]% rebar3 hex docs
===> No valid hex docs configuration found. Docs will will not be generated
Local Password:
===> Error publishing : Package or Package Version not found
```

It isn't immediately clear from the error message what is going on. I assume what is going on is since `{vsn, "git"}` is used, the current tag/branch is used, `"main"` in my case. I think it would be helpful to mention which version was attempted to be published to.

**Comment by tsloughter** [comment]
Ah yup, definitely needs to tell you the version it tried to publish for.

If you do the publishing from `main` and you have commits beyond the tag release then it'll be a new `vsn` and result in trying to publish for that package (which won't exist).

**Comment by starbelly** [comment]
Adding this for V7 todo. 

Edit: 

Note that `rebar3 hex docs` will not be used for publishing in v7 to be aligned with mix hex.
