### ISSUE TITLE
allows some folders, files to be added to the hex package

### ISSUE THREAD

**Issue by benoitc** [erlef/rebar3_hex#26]
I didn't see anyway yet to add some folders to the release. In my case I wanted to add a "support" folder to add some scripts and I wasn't able to include them in the source package except in the priv folder. But in that case such files would be shipped in the release. 

Having a `folders` or `packages` property in the `.app.src` for such purpose would be useful IMO. Thoughts?

**Comment by ericmj** [comment]
Check `files` under "Adding metadata to .app.src". https://hex.pm/docs/rebar3_publish

**Comment by benoitc** [comment]
ah it isn't documented on rebar3.org :) thanks!

**Comment by ericmj** [comment]
Maybe rebar3.org should link to hex.pm if they don't have full overlap?

**Comment by benoitc** [comment]
cc @tsloughter it sounds like a good idea. One way or the other would make it easier to track.

**Comment by tsloughter** [comment]
Ah, yes.

**Comment by benoitc** [comment]
Back on this issue. I just tried to use the `files` property. The annoying thing with it, is that is forcing to collect all the files here (even if we can use the wildcard). 

What about adding an `extra_files` property that would only add extra files and still use the the list retrieved by the plugin? We could also have an `exclude_files` for that purpose. 

Thoughts?

**Comment by starbelly** [comment]
Closing this as resolved via #40 . Please re-open if there is other outstanding problems.
