### ISSUE TITLE
Owner add command cannot add maintainers as documented

### ISSUE THREAD

**Issue by eproxus** [erlef/rebar3_hex#300]
The documentation states:

```command
$ rebar3 help hex owner
...
Supported command combinations:
 ...
 rebar3 hex owner add <package> <username> <level>
...
```

But running `rebar3 hex owner add foo bar maintainer` add the user as an owner instead. Using `rebar3 hex owner add foo bar --level maintainer` works, as documented further down in the man page.

What is a maintainer btw? It's not documented anywhere on Hex or in Mix/Rebar...

**Comment by starbelly** [comment]
Fully agree 💯 ... 

This should be documented in hex.pm and perhaps in rebar3_hex as well. 

One distinction is a "full" owner can transfer a package, where as a maintainer can only publish, retire, etc. iirc. Would ask @ericmj to correct me if I'm wrong.

The levels have a more use in organizations also iirc.
