### ISSUE TITLE
Conditional mix.exs deps are invalid

### ISSUE THREAD

**Issue by mpope9** [erlef/rebar3_hex#307]
I'm attempting to add the latest version of [Jason](https://hex.pm/packages/jason) to an application. I'm seeing the following error message:
```
===> Dep decimal has invalid version ~> 1.0 or ~> 2.0
```

I believe it is due to [this line in the mix.exs file](https://github.com/michalmuskala/jason/blob/master/mix.exs#L31):
```elixir
defp deps() do
    [
      {:decimal, "~> 1.0 or ~> 2.0", optional: true},
...
```

Here is a repro:
```
% rebar.config
{plugins, [
    {rebar3_elixir, ".*", {git, "https://github.com/Supersonido/rebar3_elixir.git", {branch, "master"}}},
    rebar3_hex}]}.

{deps, [
    {jason, "1.3.0"}]}.
```

I didn't realized deps could be conditional until I saw this.

**Comment by tsloughter** [comment]
Yea, rebar3 does not (yet) support conditional constraints. It is an issue with rebar3 itself, not rebar3_hex which is not responsible for package resolving or fetching.

**Comment by mpope9** [comment]
Ah I see. Will close, thank you!
