### ISSUE TITLE
rebar3 hex docs --dry-run asking for my Local Password

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlef/rebar3_hex#309]
I'm using `--dry-run` in `rebar3 hex publish docs` and it asks me for `Local Password: `.

Since the documentation states

```
  --dry-run   Generates docs (if configured) but does not publish the
              docs. Useful for inspecting docs before publishing.
              [default: false]
```

I'm wondering if that's intended behaviour, or a bug, since, when my password is asked for, the documentation is already generated.

I'd like to use the `--dry-run` command for CI (I imagine the exit code code be such that a CI flow could be interrupted), to make sure the documentation is possible to generate, without uploading it.

Thanks.

**Comment by starbelly** [comment]
We can fix that up, but also I recommend using `rebar3 hex build` to inspect contents.

**Comment by paulo-ferraz-oliveira** [comment]
Oh, cool. I'd never used it. Thanks.

**Edit**: in any case I'm sure `build` does more than `publish docs` and I'm only interested in replacing a small part of a CI.

**Comment by starbelly** [comment]
@paulo-ferraz-oliveira If you CI is only doing a dry run you can simply do `build docs` 


Edit:

Note my answer doesn't resolve the issue. It shouldn't happen during a dry-run :)

**Comment by paulo-ferraz-oliveira** [comment]
Do you know if this still happens, @starbelly? I can try and find time to fix it, if it does.

**Comment by starbelly** [comment]
No, this will no longer prompt for the local password in the case of docs. Only in the case of package, but that should probably not be the case. I'll open up an issue for that one and close this.

**Comment by starbelly** [comment]
https://github.com/erlef/rebar3_hex/issues/315
