### ISSUE TITLE
search is missing packages

### ISSUE THREAD

**Issue by Licenser** [erlef/rebar3_hex#31]
Some packages seem not to be listed, for example searching for oauth2 doesn't list the `oauth2` package wich does exist.

reproduce:

```
rebar3 hex search oauth2 
p1_oauth2: 0.6.1
```

vs:

![image](https://cloud.githubusercontent.com/assets/119093/13120663/cddcf328-d57c-11e5-9c33-3e1f68164ccf.png)

**Comment by tsloughter** [comment]
Haven't you asked about this before :). Rebar3 only displays packages it can build.

**Comment by Licenser** [comment]
Ohhhh nope didn't ask about that before must have been someone else, sorry.
