### ISSUE TITLE
In GitHub Actions the plugin try push 0.0.0 version

### ISSUE THREAD

**Issue by vkatsuba** [erlef/rebar3_hex#314]
Hi All!

By some reason latest version of plugin is try to push into hex.pm version `0.0.0` of application. Here is a [link to failed CI](https://github.com/travelping/gtplib/actions/runs/3111922796/jobs/5044769001#step:5:117) where you can see:

```sh

Note : In version 7.1 this warning will be treated as an error

===> Getting log of git repo failed in /__w/gtplib/gtplib. Falling back to version 0.0.0
===> gtplib.app.src : invalid license types detected - 'Mozilla Public License 2.0'
     See https://spdx.org/licenses/ for a list of valid license identifiers

===> Getting log of git repo failed in /__w/gtplib/gtplib. Falling back to version 0.0.0
```
Here is a [pipeline for publish package](https://github.com/travelping/gtplib/blob/master/.github/workflows/hex.yaml).

Any opinions about it?

**Notes**: same approach can be used locally and all will works as expected - the issue is related only for GitHub Actions.

Best Regards,
--V

**Comment by starbelly** [comment]
@vkatsuba Hi! 😄 

This actually is more related to rebar3 itself.  In the run we can see : 

> Getting log of git repo failed in /__w/gtplib/gtplib. Falling back to version 0.0.0

This comes from `rebar_git_resource:make_vsn/2`, which rebar3_hex utilizes for getting the git version. 

That said, I'm not able to reproduce it locally, but my environment is quite different ofc. I suspect this has something to do with the version of git used by the checkout action, but will have to dig more. There was a change to make_vsn/2 in rebar3 3.14 and the version used by that erlang alpine image is 3.14.3, so possible, but at a quick glance didn't seem to be related.

**Comment by vkatsuba** [comment]
Hey @starbelly! Thanks for reply. Will close it.

Best Regards,
--V
