### ISSUE TITLE
rebar3 hex config key value always writes bitstrings

### ISSUE THREAD

**Issue by hukl** [erlef/rebar3_hex#45]
I've tried to debug another issue and added a https_proxy config setting. 
1. it was written to the hex.config but I got an error that my global rebar3.config was existing but unreadable as a consequence
2. the proxy setting is passed to http_uri:parse which fails if you pass it a binary because it is expecting a string. You should add a type conversion there. rebar3_http_hex.erl:123

**Comment by starbelly** [comment]
This can be closed per hex_core
