### ISSUE TITLE
rebar3 hex cut fails silently

### ISSUE THREAD

**Issue by Licenser** [erlef/rebar3_hex#52]
using rebar3 hex cut tends to fail silently when something goes wrong. For example i.e. when using cut to generate a new release but a `ebin/.app` file exist (due to checkouts creating them) the plugin will run through happily and not give an error but neither publish a new package (since the package can't be published due to version conflicts)

**Comment by starbelly** [comment]
This issue should be resolved in later rebar3_hex versions. Please re-open this issue if you find otherwise.
