### ISSUE TITLE
Dependencies not found with rebar3 3.3.0

### ISSUE THREAD

**Issue by elbrujohalcon** [erlef/rebar3_hex#56]
I'm trying to publish [beam_olympics](https://github.com/inaka/beam_olympics).
If I use rebar3 version 3.2.0:

``` bash
$ rebar3 hex publish
===> Verifying dependencies...
Publishing beam_olympics 1.2.0
  Description: Let's find the best beamer!
  Dependencies:
    eper ~> 0.94
    epocxy 1.1.0
    sumo_db 0.6.1
  Included files:
…
```

If I use rebar3 version 3.3.0:

``` bash
$ rebar3 hex publish
===> Verifying dependencies...
Publishing beam_olympics 1.2.0
  Description: Let's find the best beamer!
  Dependencies:

  Included files:
…
```

As you can see, the plugin can't find the dependencies with the latest version of rebar3.

**Comment by ferd** [comment]
Dis you try upgrading the hex plugin? This happens because of the lock file format change iirc and newer versions of the plugin were ready for it back around June or July I believe.

**Comment by elbrujohalcon** [comment]
Yeah, I upgraded the plugin. Although it upgraded locally because with the latest rebar3 this command doesn't seem to work:

``` bash
$ rebar3 as global plugins upgrade rebar3_hex
===> No entry for profile global in config.
===> No upgrade needed for rebar3_hex
```

**Comment by mdaguete** [comment]
The same for rebar3 3.3.1

**Comment by tsloughter** [comment]
@elbrujohalcon there is no error there in that output (assuming there isn't an upgraded available of course). But we should have the `as` provider match on `global` and not output that warning so it isn't confusing.

**Comment by tsloughter** [comment]
My bad. I had updated the plugin for the new lock format but never committed and published :(

**Comment by tsloughter** [comment]
Try a `rebar3 update` and `rebar3 as global plugins upgrade rebar3_hex` now. It should install version `3.0.0` which will work with rebar3 3.3.x

**Comment by mdaguete** [comment]
@tsloughter It works now.
Thanks.

**Comment by elbrujohalcon** [comment]
It does work, indeed. I'm closing this issue. Thank you guys!!
