### ISSUE TITLE
Make docs task configurable

### ISSUE THREAD

**Issue by yurrriq** [erlef/rebar3_hex#57]
e.g. `lfe lodox` instead of `edoc`

**Comment by tsloughter** [comment]
Good point.

**Comment by yurrriq** [comment]
Turns out we're probably gonna use the EDoc format internally going forward so this will likely become a non-issue. Closing for now. Feel free to reopen.

**Comment by yurrriq** [comment]
I don't need it immediately, but this would be cool still.
