### ISSUE TITLE
Error messages provides no hint on what is wrong

### ISSUE THREAD

**Issue by markusn** [erlef/rebar3_hex#60]
Trying to publish an Erlang package I get the following error message:

`
[<<"{\"status\":422,\"message\":\"Validation error(s)\",\"errors\":{\\"requirements\":\"is invalid\"}}">>],
`

What is requirements? There is no such keyword in the rebar.config or app.src. It could possibly be deps in rebar.config or applications in app.src. However there is no description on which what or what the problem is.

**Comment by ericmj** [comment]
Requirements are your dependencies. If the error message just says "is invalid" it's likely that entire type is wrong, but it's hard to say for sure.

**Comment by markusn** [comment]
Ok. What is the value of deps in rebar.config suppose to be when you have no dependencies? I've tried omitting the key or using {deps, []}. The result is the same in both cases.

**Comment by ericmj** [comment]
I think either should work. Can you verify that you are using the latest version of rebar3 and rebar3_hex? If you can show your project that would be helpful also.

**Comment by markusn** [comment]
Seems like updating to rebar3_hex 3.0 fixed it. Sorry for the confusion and thanks for the help!
