### ISSUE TITLE
Handle {DepName, {pkg, PkgName}} dependencies

### ISSUE THREAD

**Issue by yurrriq** [erlef/rebar3_hex#63]
As of now, I think such dependencies will result in a `bad_match` error.

**Comment by tsloughter** [comment]
Hm, could you try again with the latest rebar3_hex i could have swore I've had to do this.

**Comment by yurrriq** [comment]
I can confirm this works with [4.0.0](https://hex.pm/packages/rebar3_hex/4.0.0) on [19.2](https://github.com/NixOS/nixpkgs/blob/ad3e589c6dea250e9913909b56602fd51edddf30/pkgs/development/interpreters/erlang/R19.nix). Cheers!
