### ISSUE TITLE
Add option to not only create a commit but also tag it.

### ISSUE THREAD

**Issue by Licenser** [erlef/rebar3_hex#64]
I think something like the following would be really nice to keep tags on the repo that correspond to the release package:

```
Create 'version bump' commit? ("Y")>
Create 'v<version number>' tag? ("Y")>
Push master to origin master? ("N")> Y
```

I know this somewhat works with using the `git` version already but that itself comes with a bit of a ickyness.

**Comment by starbelly** [comment]
This has been implemented in later versions of rebar3_hex. Please reopen if you find other related issues.
