### ISSUE TITLE
Warn if publishing package with pre-release dependencies

### ISSUE THREAD

**Issue by ericmj** [erlef/rebar3_hex#69]
If a package has unstable dependencies it is regarded as unstable itself.

The hexpm server will introduce this policy in the future so we should make rebar3 users have a grace period to update their packages until it becomes an error.

**Comment by starbelly** [comment]
@ericmj I'm pretty sure this has been implemented in hexpm, is this issue stale?

**Comment by starbelly** [comment]
Closing this as stale. Please re-open if needed.

**Comment by ericmj** [comment]
It has not been implemented in hexpm yet, we are waiting for rebar3_hex to have shipped with this warning for a while. Sorry for missing your earlier ping.

**Comment by starbelly** [comment]
@ericmj no worries, re-opened

**Comment by starbelly** [comment]
@ericmj For clarity, I assume we would determine this via semver?

**Comment by ericmj** [comment]
Yes, you need to check if any of the dependencies have a pre-release component `-foo` in their version requirement.

**Comment by starbelly** [comment]
@ericmj Got it. This should be a warning vs a fatal?

**Comment by ericmj** [comment]
It should be a warning initially to help users transition. Eventually it will be a server error and then you can make it an error if it will give a better error message than the server provides. We will let you know when it becomes a server error.
