### ISSUE TITLE
Use HTTP(S)_PROXY environment variables if defined

### ISSUE THREAD

**Issue by filmor** [erlef/rebar3_hex#72]

**Comment by tsloughter** [comment]
@starbelly you think this is handled now?

**Comment by starbelly** [comment]
I wasn't sure. Looking at hex_core it is not handled there at a glance, so let's leave this one open. mix/hex provides an http_proxy option and maybe that should be moved into hex_core as well as the ability to override with an env var per the suggestion in this ticket.

**Comment by starbelly** [comment]
@filmor Many moons later 😁 rebar3 supports `http_proxy` and `https_proxy`, it's not upper case which I think is where the disconnect happened and by now you may have sussed that out already. Is this still an issue for you?

**Comment by filmor** [comment]
Our company scrapped its corporate proxy about 2 years ago :)

I do remember that things got better in-between, though.

**Comment by starbelly** [comment]
@filmor haha... ok, closing this until it becomes an issue again 😁
