### ISSUE TITLE
Password entry does not work on windows.

### ISSUE THREAD

**Issue by jkrukoff** [erlef/rebar3_hex#97]
Hex.pm password entry no longer works on windows, as the password entry prompt now mistakenly includes the trailing newline character as part of the password. Unless your hex.pm password happens to already end with a newline, this will prevent authentication from working. A possible patch is here:

https://github.com/tsloughter/rebar3_hex/pull/92

**Comment by starbelly** [comment]
@tsloughter This was closed via #92
